name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.1.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface:
    git:
      url: git@github.com:pumpkincrypto/flutter_cached_network_image.git
      path: cached_network_image_platform_interface/
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: git@github.com:pumpkincrypto/flutter_cache_manager.git
      ref: 45a980dbbe15e70c53cc05179a662473cc7945fa
      path: flutter_cache_manager/

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
