name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.3.1
environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface:
    git:
      url: git@github.com:pumpkincrypto/flutter_cached_network_image.git
      path: cached_network_image_platform_interface/
  cached_network_image_web:
    git:
      url: git@github.com:pumpkincrypto/flutter_cached_network_image.git
      path: cached_network_image_web/
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: git@github.com:pumpkincrypto/flutter_cache_manager.git
      ref: 88fbf1098cd45a6e57b304f9433be0c0e9480d41
      path: flutter_cache_manager/
  octo_image: ^2.0.0

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
